import QueryProvider from '@/providers/query.provider';
import type { Metadata } from 'next';
import { Pacifico } from 'next/font/google';
import localFont from 'next/font/local';
import { Toaster } from 'react-hot-toast';
import './globals.css';

const sfProDisplay = localFont({
  src: [
    {
      path: './fonts/SFPRODISPLAYREGULAR.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/SFPRODISPLAYULTRALIGHTITALIC.woff2',
      weight: '100',
      style: 'italic',
    },
    {
      path: './fonts/SFPRODISPLAYTHINITALIC.woff2',
      weight: '200',
      style: 'italic',
    },
    {
      path: './fonts/SFPRODISPLAYLIGHTITALIC.woff2',
      weight: '300',
      style: 'italic',
    },
    {
      path: './fonts/SFPRODISPLAYMEDIUM.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/SFPRODISPLAYSEMIBOLDITALIC.woff2',
      weight: '600',
      style: 'italic',
    },
    {
      path: './fonts/SFPRODISPLAYBOLD.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/SFPRODISPLAYHEAVYITALIC.woff2',
      weight: '800',
      style: 'italic',
    },
    {
      path: './fonts/SFPRODISPLAYBLACKITALIC.woff2',
      weight: '900',
      style: 'italic',
    },
  ],
  variable: '--font-sfpro',
  display: 'swap',
});

const pacifico = Pacifico({
  subsets: ['vietnamese'],
  weight: ['400'],
  variable: '--font-pacifico',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${sfProDisplay.variable} ${pacifico.variable} antialiased`}
      >
        <Toaster />
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
